// GENERATED by scripts/build-voxel-atlas.mjs — do not edit by hand.
// Source pack: vanilla

/** Tile size in px (Minecraft's native block texture resolution). */
export const TILE_PX = 16;
/** Atlas is a 8x8 grid of tiles. */
export const ATLAS_TILES = 8;
export const ATLAS_PX = 128;

/** Atlas tile coordinates, [col, row]. */
export const TILE = {
  grassTop: [0, 0],
  grassSide: [1, 0],
  dirt: [2, 0],
  coarseDirt: [3, 0],
  rootedDirt: [4, 0],
  moss: [5, 0],
  calcite: [6, 0],
  diorite: [7, 0],
  andesite: [0, 1],
  stone: [1, 1],
  cobble: [2, 1],
  gravel: [3, 1],
  stonebrick: [4, 1],
  mossyCobble: [5, 1],
  dripstone: [6, 1],
  tuff: [7, 1],
  deepslate: [0, 2],
  cobbledDeepslate: [1, 2],
  coalOre: [2, 2],
  ironOre: [3, 2],
  goldOre: [4, 2],
  lapisOre: [5, 2],
  logSide: [6, 2],
  logEnd: [7, 2],
  plank: [0, 3],
  beam: [1, 3],
  leaves: [2, 3],
  shortGrass: [3, 3],
  tallGrassTop: [4, 3],
  tallGrassBottom: [5, 3],
  fern: [6, 3],
  poppy: [7, 3],
  dandelion: [0, 4],
  pinkPetals: [1, 4],
  hangingRoots: [2, 4],
  plaster: [3, 4],
  quartz: [4, 4],
  quartzChiseled: [5, 4],
  quartzPillar: [6, 4],
  roof: [7, 4],
  roofDark: [0, 5],
  roofPlain: [1, 5],
  ridge: [2, 5],
  wool: [3, 5],
  gold: [4, 5],
  window: [5, 5],
  shu: [6, 5],
  lanternLit: [7, 5],
  glow: [0, 6],
} as const satisfies Record<string, readonly [number, number]>;

export type TileName = keyof typeof TILE;
